services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "9997:80"
    depends_on:
      - postgres
    networks:
      - backend
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_gateway
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "9998:5432"
    networks:
      - backend
  redis: 
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
  
volumes:
  postgres_data:
    driver: local