services:
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "9999:9999"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  # api: 
  # networks:
  #   backend:
  #     driver: bridge
  #   payment-processor:
  #     external: true

  redis: 
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge